// UI fixture only. Never used by the application or presented as model output.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1050}, deviceScaleFactor:1});
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const output = path.join(__dirname, '../test-results'); fs.mkdirSync(output, {recursive:true});
  await page.route('https://fonts.googleapis.com/**', route => route.abort());
  await page.route('**/api/status', route => route.fulfill({json:{ready:false,label:'Setup needed'}}));
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:8000', {waitUntil:'networkidle'});
  await page.getByRole('link', {name:'Investigation', exact:true}).click();
  assert.equal(await page.locator('#status').innerText(), 'Setup needed');
  assert.equal(await page.locator('#generate').isDisabled(), true);
  await page.locator('#scenario').selectOption('streaming');
  await page.waitForFunction(() => document.getElementById('incident').value.includes('19:42 UTC'));
  assert((await page.locator('#incident').inputValue()).includes('19:42 UTC'));
  await page.screenshot({path:path.join(output,'northstar-setup.png'),fullPage:true});
  await page.route('**/api/status', route => route.fulfill({json:{ready:true,label:'UI TEST · NOT LIVE'}}));
  const text = '## Observed facts\n- UI test fixture: playback freezes; sampled playlists return 200 and some segments return 404.\n## Next checks\n- Compare repeated same-stream CDN and authorized origin playlists for sequence progression.\n- Trace a failed segment to its referencing playlist and inspect the effective cache behavior.\n## Resolution path\n- If the evidence confirms an unsuitable playlist cache policy, review the compatible target, origin load, and approval before restoring the intended policy. Verify playlist progression and playback afterward.\n## Missing evidence\n- Current edge/origin comparison, deployed policy, impact scope, compatibility, capacity, and approval are not supplied.\n';
  const source = {number:1,document_id:'NS-RB-001',version:'1.0',filename:'01-playlist-freshness.md',title:'Live HLS playlist freshness',excerpts:['UI TEST EXCERPT — not an API response. Compare repeated CDN and authorized origin samples. <script>window.injected=true</script>']};
  await page.route('**/api/triage', route => route.fulfill({json:{text,annotations:[{index:text.indexOf('\n- Trace'),source:1}],sources:[source]}}));
  await page.reload({waitUntil:'networkidle'});
  await page.locator('#scenario').selectOption('streaming');
  await page.waitForFunction(() => document.getElementById('incident').value.includes('19:42 UTC'));
  await page.getByRole('button', {name:/Generate triage brief/}).click();
  await page.getByText('Ready for review', {exact:true}).waitFor();
  assert.equal(await page.locator('#brief h3').count(), 4);
  await page.screenshot({path:path.join(output,'northstar-ui-test.png'),fullPage:true});
  await page.getByRole('button', {name:'Inspect source 1'}).click();
  assert.equal(await page.locator('#source-dialog').isVisible(), true);
  assert((await page.locator('#source-excerpts').innerText()).includes('<script>'));
  assert.equal(await page.evaluate(() => window.injected), undefined);
  await page.getByText('Read full knowledge document', {exact:true}).click();
  await page.waitForFunction(() => document.getElementById('document-content').textContent.includes('NS-RB-001'));
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#source-dialog').isVisible(), false);
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({path:path.join(output,'northstar-mobile-test.png'),fullPage:true});
  await page.getByRole('link', {name:'Operations Dashboard', exact:true}).click();
  await page.getByRole('button', {name:'Investigate Frozen live stream', exact:true}).press('Enter');
  await page.waitForFunction(() => document.getElementById('incident').value.includes('19:42 UTC'));
  assert.equal(await page.locator('#brief').isVisible(), false);
  assert.equal(await page.locator('#source-list').innerText(), '');
  assert.equal(await page.locator('#result-label').innerText(), 'Awaiting context');
  assert((await page.locator('#question').inputValue()).includes('CloudFront'));
  await page.route('**/api/triage', route => route.fulfill({status:502,json:{detail:'UI test: simulated upstream failure.'}}));
  await page.getByRole('button', {name:/Generate triage brief/}).click();
  await page.getByText('UI test: simulated upstream failure.').waitFor();
  assert.equal(await page.locator('#brief').isVisible(), false);
  assert.equal(await page.locator('#generate').isEnabled(), true);
  assert.deepEqual(errors, []);
  console.log('PASS: setup state, exact sample, brief render, native citation control, safe excerpts, full document, Escape, mobile width, keyboard alert handoff clearing prior brief/sources, explicit failure without stale output; no page errors. Mocked output is UI-test-only.');
  await browser.close();
})().catch(error => {console.error(error);process.exit(1)});
