// UI proof only: synthetic replay and real local fixtures, no model calls.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1100}});
    const errors = [], posts = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (request.method() === 'POST') posts.push(request.url()); });
    await page.route('https://fonts.googleapis.com/**', route => route.abort());
    await page.route('**/api/status', route => route.fulfill({json:{ready:false,label:'Setup needed'}}));
    await page.route('**/api/triage', route => route.fulfill({status:500,json:{detail:'Unexpected model request'}}));
    const output = path.join(__dirname, '../test-results'); fs.mkdirSync(output, {recursive:true});
    const button = name => page.getByRole('button', {name,exact:true});
    const overview = () => page.getByRole('link', {name:'Operations Dashboard',exact:true}).click();
    const loaded = term => page.waitForFunction(term => document.getElementById('incident').value.includes(term), term);
    const rowCount = () => page.locator('#alert-rows tr').count();
    const screenshot = name => page.screenshot({path:path.join(output,name+'.png'),fullPage:true});
    await page.clock.install({time:new Date('2026-10-06T20:00:00Z')});
    await page.goto(process.env.BASE_URL || 'http://127.0.0.1:8000', {waitUntil:'networkidle'});
    await page.clock.pauseAt(new Date('2026-10-06T20:00:05Z'));
    await button('Replay').click();
    assert(await page.locator('#monitoring-view').isVisible());
    assert.equal(await page.locator('.metric-card svg').count(), 6);
    assert.equal(await rowCount(), 1);
    assert.equal(await page.locator('#log-list .log-row').count(), 8);
    const chart = await page.locator('.chart-line').first().getAttribute('d');
    const log = await page.locator('#log-list').innerText();
    await page.clock.runFor(5000);
    assert.notEqual(await page.locator('.chart-line').first().getAttribute('d'), chart);
    assert.notEqual(await page.locator('#log-list').innerText(), log);
    await button('Pause simulation').click();
    const time = await page.locator('#replay-time').innerText();
    await page.clock.runFor(120000);
    assert.equal(await page.locator('#replay-time').innerText(), time);
    assert.equal(await rowCount(), 1);
    await button('Resume simulation').click();
    await page.clock.runFor(9000);
    assert.equal(await rowCount(), 1);
    await screenshot('monitoring-desktop');
    await button('Investigate Frozen live stream').click(); await loaded('19:42 UTC');
    assert(await page.locator('#triage-view').isVisible());
    assert.equal(await page.locator('#scenario').inputValue(), 'streaming');
    assert.equal(await page.evaluate(() => document.activeElement.id), 'incident');
    assert((await page.locator('#question').inputValue()).includes('CloudFront'));
    assert(await page.locator('#generate').isDisabled());
    await page.locator('#question').fill('Keep this draft while navigating.');
    await overview(); await page.goBack();
    assert(await page.locator('#triage-view').isVisible());
    assert.equal(await page.locator('#question').inputValue(), 'Keep this draft while navigating.');
    await page.goForward(); await page.clock.runFor(1000);
    assert.equal(await rowCount(), 2);
    assert.equal(await page.locator('#alert-count').innerText(), '2');
    assert((await page.locator('#alert-announcement').innerText()).includes('Unhealthy EC2 application'));
    assert.equal(await page.locator('.metric-amber .metric-value').innerText(), '96');
    assert((await page.locator('#log-list').innerText()).includes('root filesystem 96%'));
    await button('Investigate Unhealthy EC2 application').click(); await loaded('96%');
    assert.equal(await page.locator('#scenario').inputValue(), 'compute');
    assert((await page.locator('#question').inputValue()).includes('prior case'));
    assert.equal(await page.locator('#brief').isVisible(), false);
    await screenshot('monitoring-handoff');
    await overview(); await page.clock.runFor(29000);
    assert.equal(await rowCount(), 2);
    await page.clock.runFor(1000);
    assert.equal(await rowCount(), 3);
    assert.equal(await page.locator('#replay-time').innerText(), '20:16:00 UTC');
    assert((await page.locator('#log-list').innerText()).includes('DatabaseConnections 492'));
    assert((await page.locator('#alert-schedule').innerText()).includes('All three'));
    const dbCard = page.locator('.metric-card').filter({has:page.getByRole('heading', {name:'RDS connections',exact:true})});
    assert.equal(await dbCard.locator('.metric-value').innerText(), '492');
    assert.equal(await dbCard.locator('.metric-condition').innerText(), 'Elevated');
    await screenshot('monitoring-rds-desktop');
    await button('Investigate RDS connection pressure').click(); await loaded('bw-catalog-db');
    assert.equal(await page.locator('#scenario').inputValue(), 'database');
    assert((await page.locator('#question').inputValue()).includes('RDS CPU'));
    assert.equal(await page.locator('#brief').isVisible(), false);
    await screenshot('monitoring-rds-handoff');
    await page.route('**/api/sample?scenario=streaming', route => route.fulfill({status:503,json:{detail:'UI test: sample temporarily unavailable.'}}));
    await overview(); await button('Investigate Frozen live stream').click();
    await page.getByText('UI test: sample temporarily unavailable.', {exact:true}).waitFor();
    assert.equal(await page.locator('#incident').inputValue(), '');
    assert.equal(await page.locator('#question').inputValue(), '');
    assert(await page.locator('#load-sample').isEnabled());
    await page.unroute('**/api/sample?scenario=streaming');
    await button('Load demo').click(); await loaded('19:42 UTC');
    await overview(); await page.clock.runFor(600000);
    assert.equal(await rowCount(), 3);
    assert.equal(await page.locator('#log-list .log-row').count(), 8);
    for (const width of [1024,768,390]) {
      await page.setViewportSize({width,height:1000});
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `No page overflow at ${width}px`);
    }
    await screenshot('monitoring-mobile');
    await button('Investigate Unhealthy EC2 application').click(); await loaded('96%');
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await overview(); await button('Replay').click();
    assert.equal(await rowCount(), 1);
    assert.equal(await page.locator('#replay-time').innerText(), '20:10:00 UTC');
    assert.deepEqual(posts, []); assert.deepEqual(errors, []);
    console.log('PASS: metrics/logs, 15-second alert, pause/resume/replay, bounded rows, all three handoffs, 45-second RDS alert, draft/back navigation, failure/retry, responsive width; zero model requests and page errors.');
  } finally { await browser.close(); }
})().catch(error => {console.error(error);process.exit(1)});
